baseURL = 'https://zanderwilkinson.github.io/Personal-Website/'
languageCode = 'en-gb'
title = 'Alexander Wilkinson'

[params]
  name = 'Alexander Wilkinson'
  role = 'MSc Bioinformatics Student · First-Class Engineering Graduate'
  
  github = 'https://github.com/zanderwilkinson'

[outputs]
  home = ['HTML']
